workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Flutter build
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build Android AAB
        script: flutter build appbundle \
          --release \
          --obfuscate \
          --split-debug-info=build/secure
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your-email@example.com
        on_success: always
        on_failure: always
