workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean build
        script: flutter clean
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.aab
