workflows:
  opay_release_build:
    name: Opay Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - opay_keystore
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Clean build
        script: flutter clean

      - name: Build AAB with obfuscation
        script: |
          flutter build appbundle \
            --release \
            --obfuscate \
            --split-debug-info=build/outputs/debug-info

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your-email@example.com # Optional for build notifications
