workflows:
  android-release:
    name: Android Release Build
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean build
        script: flutter clean
      - name: Build AAB (v2 embedding)
        script: flutter build appbundle --release --obfuscate --split-debug-info=build/secure
    artifacts:
      - build/app/outputs/**/*.aab
