name: opay
description: A mobile banking app clone
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  uuid: ^4.2.2
  go_router: ^12.1.1
  firebase_messaging: ^14.7.6
  pdf: ^3.10.4
  printing: ^5.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  pdf_image_renderer: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
image_picker: ^1.0.4
firebase_storage: ^11.5.6
flutter:
  assets:
    - assets/default_user.png
flutter:
  assets:
    - assets/logo.png
