name: opay_clone
description: A mobile banking app clone
publish_to: 'none' # Prevents accidental publishing
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # Recommended: Broad enough for Dart 3, good for modern Flutter apps.
                        # You can make this more specific if you want to lock to a Flutter release.
                        # For example, ">=3.10.0 <4.0.0" if you're on a very recent Flutter stable.

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core and Authentication
  firebase_core: ^2.31.0 # Check pub.dev for the absolute latest stable version
  firebase_auth: ^4.19.0 # Check pub.dev for the absolute latest stable version
  cloud_firestore: ^4.15.0 # Check pub.dev for the absolute latest stable version
  firebase_messaging: ^14.7.15 # Check pub.dev for the absolute latest stable version
  firebase_storage: ^11.5.7 # Check pub.dev for the absolute latest stable version

  # State Management
  provider: ^6.1.1 # Stable and widely used

  # UI/UX and Utilities
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1 # For internationalization and date formatting
  flutter_svg: ^2.0.10 # For SVG asset handling
  shared_preferences: ^2.2.2 # For local key-value storage
  font_awesome_flutter: ^10.7.0 # For Font Awesome icons
  uuid: ^4.2.2 # For generating unique IDs

  # Navigation
  go_router: ^12.1.1 # A popular package for declarative routing

  # PDF Generation and Printing
  pdf: ^3.10.4 # For creating PDF documents
  printing: ^5.12.1 # For printing documents
  pdf_image_renderer: ^0.7.0 # For rendering PDF pages as images

  # File System and Permissions
  path_provider: ^2.1.3 # For accessing common file system locations
  permission_handler: ^11.3.2 # For handling platform permissions

  # Device Features and Security
  share_plus: ^7.2.2 # For sharing content
  flutter_secure_storage: ^9.0.1 # For secure local storage
  local_auth: ^2.1.7 # For local device authentication (fingerprint/face ID)
  image_picker: ^1.1.2 # For picking images from gallery/camera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Recommended for static analysis and code quality

flutter:
  uses-material-design: true
  assets:
    - assets/default_user.png
    - assets/logo.png

# Keep this comment if it's genuinely a reminder for your team/yourself
# Trigger build
