# Full code for pubspec.yaml
name: opay_clone
description: A mobile banking app clone
publish_to: 'none' # Prevents accidental publishing
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0" # IMPORTANT: Update this to support Dart 3+

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core and Authentication (updated to more recent common versions as of current time)
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.5.7

  # State Management
  provider: ^6.1.1

  # UI/UX and Utilities
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  uuid: ^4.2.2

  # Navigation
  go_router: ^12.1.1

  # PDF Generation and Printing
  pdf: ^3.10.4
  printing: ^5.12.1
  pdf_image_renderer: ^0.7.0

  # File System and Permissions
  path_provider: ^2.1.3
  permission_handler: ^11.3.2

  # Device Features and Security
  share_plus: ^7.2.2
  flutter_secure_storage: ^9.0.1
  local_auth: ^2.1.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_user.png
    - assets/logo.png
