# Full code for .github/workflows/main.yml
name: Flutter CI/CD # A descriptive name for your workflow

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main # This workflow also runs for pull requests targeting 'main'

jobs:
  build_apk:
    runs-on: ubuntu-latest # Specifies the operating system for the build environment

    steps:
      - name: Checkout Repository # Step to get your code from GitHub
        uses: actions/checkout@v4 # Use the latest stable version of the checkout action

      - name: Set up Java Development Kit # Essential for Android builds with modern Flutter
        uses: actions/setup-java@v4 # Use the latest stable version of the Java setup action
        with:
          distribution: 'temurin' # A common and reliable Java distribution
          java-version: '17' # Flutter 3+ and recent Android tools typically require Java 17

      - name: Set up Flutter SDK # Step to set up the Flutter environment
        uses: subosito/flutter-action@v2 # Use the latest stable version of the Flutter action
        with:
          channel: 'stable' # Use the stable Flutter channel

      - name: Get Flutter dependencies # Downloads all packages listed in pubspec.yaml
        run: flutter pub get

      - name: Run Flutter Doctor (Optional, for CI debugging)
        run: flutter doctor -v # Provides detailed info on the Flutter setup in CI, helpful if builds fail

      - name: Build Android APK # The actual command to build the release APK
        run: flutter build apk --release --target-platform android-arm64 # Builds a release APK optimized for 64-bit ARM devices

      - name: Upload APK artifact # Makes the generated APK available for download
        uses: actions/upload-artifact@v4 # Use the latest stable version of the upload-artifact action
        with:
          name: release-apk # The name of the artifact (how it will appear on GitHub)
          path: build/app/outputs/flutter-apk/app-release.apk # The path to the generated APK file
          retention-days: 7 # How long the artifact will be kept on GitHub's servers

